### ISSUE TITLE
Q: Would you consider this package to be viable for Production.

### ISSUE THREAD

**Issue by sugoidesune** [Nativescript-Vue-Web/Nativescript-Vue-Web#149]
As we are looking for codesharing with vue and nativescript this package has piqued our interest. I didn't have much time to dig into the peculiarities of working with it and thought I'd just go ahead and ask If this would work.

Thank you.

**Comment by yerol** [comment]
Hi,

This package is currently bundled with the nativescript-vue cli plugin and functional. Although there are some issues with the cli plugin itself because of poor maintenance, but web components will work. 
As for the maintenance of this package itself, we have provided all the required functionality to map components to their NS-Vue equivalents, but going forward, because of a misalignment in development strategy, we will be focusing our efforts in VueXP package, which will have its own cli plugin and components. This package is currently in development and you are more than welcome to contribute.

Thanks

**Comment by sugoidesune** [comment]
The VueXP project didn't show up in our googlage. Thank you, looks promising.
